config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "welcome#show"

  get "/register", controller: "users", to: "users#new"
  get "/register", controller: "users", to: "users#create"
  get "/dashboard", controller: "users", to: "users#show"
  get "/wishlist", controller: "users", to: "users#wishlist"
  # resources :users, only: [:new, :create, :show] do
  #   resources :wishlists, only: [:new, :create, :show, :edit, :update]
  # end

  get '/login', to: "users#login_form"
  post '/login', to: "users#login_user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_current_user

  private

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    if !current_user
      flash[:error] = "You must be logged in to view this page"
      redirect_to root_path
    else
      @user = User.find(params[:id])
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You have successfully registered and are logged in!"
      redirect_to dashboard_path
    else
      flash[:error] = @user.errors.full_messages.to_sentence
      render :new
    end
  end

  def login_form
  end

  def login
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome back, #{user.email}!"
      redirect_to dashboard_path
    else
      flash[:error] = "Incorrect email or password"
      redirect_to root_path
    end
  end

  def logout
    session.clear
    flash[:success] = "You have been logged out"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpListFE</title>
      <h1>HelpList</h1>
          <h2>Helping Humans Help Humans</h2>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Home", root_path, class: "nav-link" %> 
      <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
      <%= link_to "Wishlist", wishlist_path, class: "nav-link" %>
    </section>
    </nav>

        <section class="log-out">
      <% if @current_user %>
        <p><%= @current_user.email %></p>
        <%= link_to "Log Out", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Log In", login_path %>
      <% end %>
    </section>
    </nav>
    
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Register with HelpList</h1>
<%= form_with model: @user do |form| %>
  <%= form.label :email, "Email:" %>
  <%= form.text_field :email %>
  <%= form.label :password, "Password:" %>
  <%= form.password_field :password %>
  <%= form.label :password_confirmation, "Password:" %>
  <%= form.password_field :password_confirmation %>
  <%= radio_button_tag(:user, "Donor") %>
  <%= label_tag(:donor, "I am registering as a Donor!") %>
  <%= radio_button_tag(:user, "Recipient") %>
  <%= label_tag(:donor, "I am registering as a Recipient!") %>
  <%= form.submit "Register" %>

app/views/welcome/show.html.erb
<%= form_with url: "/login", method: :get do |form| %>
  <%= form.label :email, "Email:"%>
  <%= form.text_field :email %>
  <%= form.label :password, "Password:" %>
  <%= form.password_field :password %>
  <%= form.submit "Login" %> 
<% end %>
<%= button_to "Login with Google", "/auth/google_oauth2"  %>

<%= link_to "Create an account", "/register" %>

<%= link_to  "Do you or someone you know need help?" %>
# add path to google maps